### ISSUE TITLE
Performance issue of CPU

### ISSUE THREAD

**Issue by kootenpv** [anachronic/importmagic.el#13]
It's also mentioned here: https://github.com/jorgenschaefer/elpy/issues/1230

The problem is that sometimes the process hangs and then uses the CPU fully. Do you know what could be the solution to this?

**Comment by anachronic** [comment]
I've never had such issues with it, honestly. Can you provide an example that would cause the process to hang?

**Comment by anachronic** [comment]
I'm closing this due to null feedback, if this issue is still bothering anyone, please open a new issue and we'll take it from there.
