### ISSUE TITLE
Use python-shell-interpreter instead of hardcoded python.

### ISSUE THREAD

**Issue by anachronic** [anachronic/importmagic.el#14]
This has been requested in #3 and would solve #10 if error messages were more accurate. Issue can be closed after

1. Error messages for `importmagic` and/or `epc` *are not found* and *running python process failed* (which do not exist right now) are separated. Right now the default behavior is having only the first error message for both cases.
2. `importmagic.el` uses the `python-shell-interpreter` variable in order to find the python executable. This was ultimately the problem in #10.
3. Such cases have tests.

I'll mention #12 aims to fix this but it's a little buggy atm.

**Comment by ahonnecke** [comment]
I'm running into this (as a result of my project being in pipenv).  I'd be happy to help or qa anything that happens with this.

**Comment by anachronic** [comment]
I am genuinely sorry about the delay. Expect changes (I can promise at least a `devel` branch) to this in a couple hours

**Comment by anachronic** [comment]
Alright, build is failing on travis (still figuring out what's happening there), but tests run fine locally.

@ahonnecke could you try the `devel` branch locally? You can choose an interpreter for python by customizing or using `setq-default` and setting the `importmagic-python-interpreter` variable. It defaults to whatever `python-shell-interpreter` is if it's set and falls back to just `python`. Note that using `ipython` works but it is **discouraged**.

If it works I'll merge into `master` when i find out what's going on with travis and write some documentation in the readme file.

**Comment by ahonnecke** [comment]
No worries regarding the delay, thank you @anachronic  :)

As a result of trying to get this installed and set up, I think that I came to the conclusion that I was not activating my virtual environment correctly.  I'm struggling with the correct way to activate a pipenv managed virtual environment (I'm still quite new to python).

What I had been doing was setting my python interpreter to "pipenv shell && python", which got *some* things working, but not well.

Regardless, I was able to install devel and try it out, it works for me now (properly inserts imports that are unresolved).  However, it seems likely that this is because I'm activating the virtual environment correctly now (using pyvenv-workon).

I did however notice that while testing it out (I deleted an import from a file in my project and then ran importmagick-fix-symbol) that the imports it suggests are not the same path as what I had.

For instance, I have a test that was importing a TOTPDevice:
```
from django_otp.plugins.otp_totp.models import TOTPDevice, default_key
```

I remove the TOTPDevice import:
```
from django_otp.plugins.otp_totp.models import default_key
```

When I ran fix-symbol it suggested this import:
```
from dad.schema import TOTPDevice, schema
```
That file in turn contains the original include:
```
from django_otp.plugins.otp_totp.models import TOTPDevice, default_key
```

The test still works, but I don't know enough about python to know if one of those paths is "more" correct.

I don't know if that provides you enough information to say that the change is working as intended; I'm happy to check further if there's something more that I can help with but you might have to provide fairly explicit instructions.

```
Elpy Configuration

Virtualenv........: web-6EpGRwxA (/Users/ahonnecke/.pyenv/versions/web-6EpGRwxA)
RPC Python........: 3.6.5 (/Users/ahonnecke/.pyenv/versions/web-6EpGRwxA/bin/python3)
Interactive Python: python3 (/Users/ahonnecke/.pyenv/versions/web-6EpGRwxA/bin/python3)
Emacs.............: 25.3.1
Elpy..............: 1.20.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Syntax checker....: flake8 (/usr/local/bin/flake8)
```

```
;; Emacs Lisp version:
(:emacs-version "25.3.1" :jedi-version "0.2.7" :python-environment-version "0.0.2alpha0")
;; Python version:
((:version "2.7.10 (default, Oct  6 2017, 22:29:07) \n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]" :name "sys" :file nil)
 (:version "0.12.0" :name "jedi" :file "/Users/ahonnecke/.emacs.d/.python-environments/jedi/lib/python2.7/site-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/Users/ahonnecke/.emacs.d/.python-environments/jedi/lib/python2.7/site-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/Users/ahonnecke/.emacs.d/.python-environments/jedi/lib/python2.7/site-packages/sexpdata.pyc"))
;; Command line:
(:virtualenv "/usr/local/bin/virtualenv" :virtualenv-version "15.1.0\n")
;; Customization:
((jedi:complete-on-dot . t)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root . "jedi")
 (jedi:environment-virtualenv "virtualenv")
 (jedi:get-in-function-call-delay . 1000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@dev#egg=jedi")
 (jedi:key-complete .
                    [C-tab])
 (jedi:key-goto-definition .
                           [67108910])
 (jedi:key-goto-definition-pop-marker .
                                      [67108908])
 (jedi:key-related-names . "r")
 (jedi:key-show-doc . "d")
 (jedi:server-args)
 (jedi:server-command "/Users/ahonnecke/.emacs.d/.python-environments/jedi/bin/jediepcserver")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
```

**Comment by anachronic** [comment]
Thanks for testing this.

I'm glad to see that it's working. I guess a lot of people have had that same problem with virtual environments, I guess I'll rearrange some parts of the readme to make it clearer for users on how to use this.

I'll leave this up for a couple days and then I'll merge. I hope to fix the travis issues in the meantime.

About the weird import issue: I've had that import issue happen to me before and I'm 99% certain that it is `importmagic`'s fault (as in [this package](https://github.com/alecthomas/importmagic) as opposed to this one). If this is still a problem, we can discuss it in a new issue.

**Comment by anachronic** [comment]
@ahonnecke just one more question before merging: Is the import situation behaving differently in the `master` branch? I really wouldn't like to introduce regressions with this

**Comment by ahonnecke** [comment]
@anachronic 

No it does not seem to behave differently 
 - restarted emacs
 - opened the file
 - started import-magic-mode
 - removed the import
 - ran fix symbols
 - got the same result

**Comment by anachronic** [comment]
Perfect.

Will merge later today then.

Thanks again for your testing.

**Comment by anachronic** [comment]
Closing since #15 was merged. Thanks @ahonnecke so much for your help.
