### ISSUE TITLE
Archive this repository or find a new maintainer

### ISSUE THREAD

**Issue by anachronic** [anachronic/importmagic.el#19]
I have not been using Emacs now for a very long time, and I don't have time to maintain this project. In fact, #17 has stayed open **for a very long time**, and I'll admit I haven't even taken a look at it.

I'm going to archive this repository unless I can find a new maintainer before Jan 31, 2020. If anyone reading this wishes to maintain this, project, please comment here.

**Comment by anachronic** [comment]
I'm sad to say that I didn't find anyone.

I really didn't have much time to look for anyone. I'm just gonna archive.

**Comment by rudolfkral** [comment]
Hi, I would like to ask if it is still possible to maintain this.

**Comment by anachronic** [comment]
This project is currently being maintained by @ryanprior. Ryan, could you remove the archive notification in the readme?

**Comment by rudolfkral** [comment]
Cool, thanks for clarifying :)

**Comment by ryanprior** [comment]
@rudolfkral to specifically answer, yes you are welcome to help maintain. Please open an issue for anything you're working on :smile:

**Comment by anachronic** [comment]
Thanks!
