### ISSUE TITLE
Python 2.7 dislikes importmagicserver.py due to UTF-8 encoding

### ISSUE THREAD

**Issue by gchpaco** [anachronic/importmagic.el#2]
Python 2.7 breaks with a SyntaxError because of the non-ASCII character in your name, I suspect.  It's easy enough to resolve; add `# -*- coding: utf-8 -*-` to the top of the file and all's well.

And yeah, I should be using 3.x.

**Comment by anachronic** [comment]
Thanks for reporting, I'll give it a try.

**Comment by pirackr** [comment]
@anachronic I got the exactly same issue when trying importmagic mode in python2 (I used 2.7.11). Doing exactly like @gchpaco pointed does help, so I create a PR here: https://github.com/anachronic/importmagic.el/pull/4/files, hope that it could help.

**Comment by anachronic** [comment]
It's merged now. Thank you.
