### ISSUE TITLE
broken by sexpdata 0.0.4

### ISSUE THREAD

**Issue by glyph** [anachronic/importmagic.el#27]
This issue affects `importmagic.el` in a slightly different way than `jedi.el` and I don't know where to look for a log that contains a traceback, but it hangs forever on 0.0.4 and works fine on 0.0.3: https://github.com/jd-boyd/sexpdata/issues/36

**Comment by jd-boyd** [comment]
Would you mind trying to test if 0.0.5 fixed this? You need to install it from github since that version isn't released yet.

**Comment by anachronic** [comment]
I will as soon as I get an emacs setup working

**Comment by glyph** [comment]
Sorry, it's definitely fixed.

I updated https://github.com/jd-boyd/sexpdata/issues/36 https://github.com/tkf/emacs-jedi/issues/368 https://github.com/tkf/emacs-jedi/issues/348 https://github.com/tkf/python-epc/pull/12 https://github.com/tkf/python-epc/issues/11 but I missed this one :)

**Comment by anachronic** [comment]
Well that's one less issue for me, thanks
