### ISSUE TITLE
Feature request: Add a customization for the python interpreter of importmagic server

### ISSUE THREAD

**Issue by Yevgnen** [anachronic/importmagic.el#3]
Thanks for the great package. I have a suggestion. Rather than hard code a "python" in starting a epc server, it would be nice if the package could read the variable `python-shell-interpreter` or read the virtualenv settings or providing a customization of it.

**Comment by pirackr** [comment]
@Yevgnen I think we can use `pyenv-mode` to address your issue?

**Comment by dakra** [comment]
There are many different emacs virtualenv modules.
I for example use https://github.com/porterjamesj/virtualenvwrapper.el 
so please don't have a dependency to a specific one if you can just call `python-shell-interpreter` instead.

**Comment by anachronic** [comment]
I'll take a look this week. But just to be clear: you want to point to an arbitrary path for a python interpreter?

If not, could you give an example please?

**Comment by anachronic** [comment]
I'm gonna close this because of null feedback.

I'd suggest a different package for virtualenvs: [pyvenv](https://github.com/jorgenschaefer/pyvenv) is a great example.

If that's not enough or not what you guys wanted, please say so and reopen. I'm all ears (or eyes...)
