### ISSUE TITLE
Expose importmagic style configuration

### ISSUE THREAD

**Issue by danlamanna** [anachronic/importmagic.el#6]
I might be missing something, but it seems that the style configuration for `importmagic` isn't exposed.

From a brief look, maybe it makes sense for the `get_import_statement` to take a configuration alist and convert it to a dictionary (not sure how `epc` handles this) to set on the `Imports` object. Does that make sense/sound about right?

**Comment by anachronic** [comment]
Yes, it totally sounds right. I have had problems with this myself, actually.

I haven't really gotten into this problem, because importmagic's documentation isn't the best one.

I'll take a look, but you're welcome to send a PR.

**Comment by anachronic** [comment]
While your pull request does the trick, I believe alist is the way to do it. I'll close this issue once that gets done.

Btw, I'll do that myself. Thanks for your help.
