### ISSUE TITLE
how to use this package with emacs's elpy package?

### ISSUE THREAD

**Issue by ghost** [anachronic/importmagic.el#9]
hello, i use elpy mode to write python code im emacs, but the latest elpy mode remove the importmagic package, some command is no longer to use, such as elpy-importmagic-fixup, it's very conveniont, is there any method to implete it in importmagic.el?

**Comment by dakra** [comment]
Maybe offtopic but did you try py-isort?
I made a PR that lets you add/remove imports https://github.com/paetzke/py-isort.el/pull/13

**Comment by ghost** [comment]
@dakra hi,dakra, i have tried py-isort just now, but it's not satisfy me, for example, the elpy-importmagic-fixup command not only sort the imports but also remove the unused imports .... it seems that py-isor provices the sort function only

**Comment by ghost** [comment]
@dakra after google, i found some solutions for my demand, if the answer is ok i will post here ...

**Comment by humitos** [comment]
@ycz0926 please, do it :)

**Comment by anachronic** [comment]
@ycz0926 just to be sure here, your question would be how to use this along with elpy?

**Comment by ghost** [comment]
@anachronic right ~for example, how to implete the command elpy-importmagic-fixup's function fully with importmagic.el?

**Comment by anachronic** [comment]
give me some time to try, and I'll get back to you.

**Comment by ghost** [comment]
@anachronic ok :+1:

**Comment by ghost** [comment]
i have solve the problem:
1. for package sort, i use `py-isort.el`
https://github.com/paetzke/py-isort.el
2. use the `py-autoflake.el` to remove all unused imports
https://github.com/humitos/py-autoflake.el

the last configuration is here:
https://github.com/ycz0926/.emacs.d/blob/master/lisp/init-python.el#L24
before use the funtion, you must install `isort` and `autoflake` python package
```bash
$ pip install isort autoflake
```
